server:
  port: 8848
  tomcat:
    basedir: logs

db:
  num: 1
  user: ${MYSQL_USER:root}
  password: ${MYSQL_PWD:fuling}
  url:
    0: jdbc:mysql://${MYSQL_HOST:123.60.222.104}:${MYSQL_PORT:3307}/${MYSQL_DB:nacos_config}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true

nacos:
  core:
    auth:
      system.type: nacos
      default.token.secret.key: SecretKey012345678901234567890123456789012345678901234567890123456789

  security:
    ignore:
      urls: /,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**

spring:
  datasource:
    platform: mysql
  security:
    enabled: true

useAddressServer: true